---
abstract: 'Create test class classes from your existing lib/'
author:
  - 'Tom Beresford <me at tomberesford dot co dot uk>'
build_requires:
  Class::Data::Inheritable: 0
  Test::Class: 0
  Test::Class::Load: 0
  Test::More: 0
  Test::Most: 0
  base: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: testMaker
recommends:
  Class::Data::Inheritable: 0.08
  Test::Class: 0.37
requires:
  File::Find: 0
  File::Path: 0
  Getopt::Std: 0
  autodie: 0
  perl: 5.010
  strict: 0
  warnings: 0
resources:
  repository: git://github.com/beresfordt/testMaker.git
version: 1.1
